### ISSUE TITLE
No 'Requirements.txt'

### ISSUE THREAD

**Issue by Catlost** [CodingCraftYT/chatbot-streamlit-openai#1]
Good evening from europe,

CodingCraftYT, i want to test this code and modify it but there´s no "requirements.txt", would you add it or tell me the packages that you need to run it. 

Thanks so much :)! 
Great work!

**Comment by CodingCraftYT** [comment]
Hi there,

I've added the requirements.txt file. Thanks for your support!

Best regards,
CodingCraftYT
